# Generated by Django 5.0.7 on 2024-07-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='description',
            field=models.TextField(default='Description', help_text='Feature Description'),
        ),
        migrations.AddField(
            model_name='feature',
            name='name',
            field=models.CharField(default='House', help_text='Feature Name', max_length=250),
        ),
    ]
